### ISSUE TITLE
Release 3.0.1 Tracker

### ISSUE THREAD

**Issue by earlephilhower** [esp8266/Arduino#8176]
[Reference](https://github.com/esp8266/Arduino/tree/master/package#creating-a-release-for-maintainers) for details.

- [X] 1. Make sure that no issues or PRs are assigned to the milestone to be released.

- [X] 2. Open a new issue to track activities.

- [X] 3. Assemble release notes.

- [X] 4. Make a PR with the following, Wait for CI and merge.  #8177

   * [platform.txt](https://github.com/esp8266/Arduino/blob/master/platform.txt)
   * [package.json](https://github.com/esp8266/Arduino/blob/master/package.json)
   * [TZ.h](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/TZ.h) (<= `cd tools; ./TZupdate.sh`)

- [X] 5. Wait until the release notes have been checked by other maintainers (can be changed afterwards anyway)

- [X] 6. Tag the latest commit on the master branch, then push it to esp8266/Arduino
      add: `git tag -a -m "Release 3.0.0" 3.0.0; git push origin 3.0.0`
      remove: `git tag -d X.Y.Z; git push --delete origin X.Y.Z`

- [X] 7. Wait for CI build for the tag to pass (in `Actions` menu)

- [X] 8. Check that the new (draft) release has been created (no editing at this point!), see https://github.com/esp8266/Arduino/releases.

- [X] 9. Check that the boards manager package .zip file has been successfully uploaded as a release artifact.

- [X] 10. Check that the package index downloaded from https://arduino.esp8266.com/stable/package_esp8266com_index.json contains an entry for the new version (it may not be the first one).

- [X] 11. Navigate to [release list in Github](https://github.com/esp8266/Arduino/releases), press "Edit" button to edit release description, paste release notes, and publish it.

- [X] 12. In the issue tracker, remove "staged-for-release" label for all issues which have it, and close them. Close the milestone associated with the released version (the milestone should be empty per point 1 above)

- [X] 13. Check that https://arduino-esp8266.readthedocs.io/en/latest/ has a new doc build for the new tag, and that "stable" points to that build. If a new build did not trigger, log into readthedoc's home here https://readthedocs.org/ (account must have been added to project as maintainer) and trigger it manually.

- [X] 14. Create a commit to the master branch, updating:

    * The version in platform.txt and package.json files. This should correspond to the version of the *next* milestone, plus `-dev` suffix. E.g. `3.1.0-dev`.
    * In main README.md go to "Latest release" section, change version number in the readthedocs link to the version which was just released, and verify that all links work.

**Comment by earlephilhower** [comment]
3.0.1 released.
